### PR TITLE
Minor changes from TB_01 to TB_05

### PR DESCRIPTION
**Pull request by ialcon**
Mainly typos here and there, and adding/moving a couple of sentences in *TB_02*. As you will see, for the extra lines that I added in *TB_02* (e.g. `tbtrans RUN.fdf > TBT.out`) I tried to add some comments for those, but for some reason *Markdown* was not working on those lines... I tried to figure out how to fix this, but didn't really find the way. I'm sure that, in case you decide to keep these extra lines, you will know how to format those side-comments correctly (I will be happy to learn that as well).

So, by now, just a start.

### CODE REVIEW

**Comment by zerothi** [comment]
thanks a lot for this, let me know when you want me to merge/do stuff! ;)

**Comment by ialcon** [comment]
Hi @zerothi, you may go on with merging and accepting/discarding the various changes. By now I've gone until *TB_05*. Once you merge I will sync my fork to the upstream, and then I will continue with reviewing the tutorials *TB_06* up to *TB_09*. In *TB_05* I wanted to add some extra lines in the **Exercices** section to physically separate the bullet point *Bulk transmission* from point 4 and the bullet point *The bulk DOS* from point 5. I tried it adding some extra lines such as `"    \n"` or `"\n"`, but it didn't work... If you know the way to do this, I think it would be nicer to provide some space there, so that it is easier to see the separation of text within each point. Just aesthetics, but why not? :smile:

**Comment by zerothi** [comment]
> Hi @zerothi, you may go on with merging and accepting/discarding the various changes. By now I've gone until _TB_05_. Once you merge I will sync my fork to the upstream, and then I will continue with reviewing the tutorials _TB_06_ up to _TB_09_. In _TB_05_ I wanted to add some extra lines in the **Exercices** section to physically separate the bullet point _Bulk transmission_ from point 4 and the bullet point _The bulk DOS_ from point 5. I tried it adding some extra lines such as `" \n"` or `"\n"`, but it didn't work... If you know the way to do this, I think it would be nicer to provide some space there, so that it is easier to see the separation of text within each point. Just aesthetics, but why not? 😄

Yeah, that space would be nice, but it would require some hacky work-arounds entering directly html code.. I think its safer to let it be ;)

**Comment by zerothi** [comment]
Thanks a ton @ialcon.

I can see that you worked on `main` on your local repo. This will cause you problems, right now. ;)
To add to this, you also changed the `main` on your own remote (which is now very different from my main).

My suggestion would be that you never touch your remote main, I can help you fix it later.

I think, for your own usability, it would be simpler if you did something like this (start over in a new folder):
```shell
git clone git@github.com:zerothi/ts-tbt-sisl-tutorial.git
cd ts-tbt-sisl-tutorial
git remote add mine git@github.com:ialcon/ts-tbt-sisl-tutorial.git
```
Now you have 2 remotes the `origin` (which is `zerothi/ts-tbt-sisl-tutorial`), and `mine` which is *your* forked repo.

The working scheme would then be:
1. Checkout main, and ensure it is up to date `git checkout main ; git pull`
2. Now branch it off and start working: `git checkout -b new-work`
3. Commit things ....
4. Push your new branch to your own remote: `git push mine new-work`
5. Create a pull-request

I think this workflow will make it a bit simpler for you (the same thing would apply to sis).

If it does not make sense, let me know!

**Comment by ialcon** [comment]
Hi @zerothi, 

You see why it was good for me to practice with the tutorials before getting into `sisl`... :relieved:

So... yes, I had no idea that working directly from my repository (fork) could be an issue, but if it is not the usual way to work I will, of course, work on changes locally. Let me note that, in my repository there was a note stating that my repo was *1 commit behind ... yours*, so I simply clicked on `Sync` and now, in principle, is up to date with `zerothi/ts-tbt-sisl-tutorial`. 

In any case, I am happy to learn how to do all the process locally following your procedure. One question here though. As of now, I've been making progress on the tutorials (I mean, doing them as a good student :smiley:) locally on my machine, here:

`/home/ialcon/TBT-TS-sisl-workshop/tarball/sisl-TBT-TS`

I understand that there is no problem with, at the same time, follow your instructions and work on the **corrections** of the tutorials within my *GitHub* folder:

`/home/ialcon/gitHub`

right? I remember you told me that having `sisl` installed and then, simultaneously, cloning the development version from your repository was not a good idea. However, I guess that this *does not* apply to the `ts-tbt-sisl-tutorial`... or does it? It is because I was not completely sure about this that I decided to work directly from the forked repository (`main` branch). 

If you may clarify this, then I will go on with your instructions - I may have couple of questions on those, but let me go step by step...

Thanks for the guidance!

**Comment by zerothi** [comment]
> You see why it was good for me to practice with the tutorials before getting into `sisl`... 😌
Hehe, pracitice is always good ;)

> So... yes, I had no idea that working directly from my repository (fork) could be an issue, but if it is not the usual way to work I will, of course, work on changes locally. Let me note that, in my repository there was a note stating that my repo was _1 commit behind ... yours_, so I simply clicked on `Sync` and now, in principle, if up to date with `zerothi/ts-tbt-sisl-tutorial`.

It is generally not an issue, I just find the above more stringent, if you always worked on *your* fork, then you would have to have a branch which tracks my `main` something like this would have been the workflow then:
```shell
git remote add zerothi git@github.com:zerothi/ts-tbt-sisl-tutorial.git
git fetch zerothi
git checkout -t zerothi/main -b zerothi-main
```
now everytime you want to do something, you would have to this:
```shell
git checkout zerothi-main
git pull
git branch new-work
# ... do work
git push new-work
```
either approach is fine, as long as you are consistent ;)

> 
> In any case, I am happy to learn how to do all the process locally following your procedure. One question here though. As of now, I've been making progress on the tutorials (I mean, doing them as a good student 😃) locally on my machine, here:
> 
> `/home/ialcon/TBT-TS-sisl-workshop/tarball/sisl-TBT-TS`
> 
> I understand that there is no problem with, at the same time, follow your instructions and work on the **corrections** of the tutorials within my _GitHub_ folder:
> 
> `/home/ialcon/gitHub`
> 
> right?

Hmm, no, when working with these tutorials you should preferentially do it *in the source tree*. :)
The reason is that you won't copy back things that were already fixed :)

> I remember you told me that having `sisl` installed and then, simultaneously, clone the development version from your repository was not a good idea. However, I guess that this _does not_ apply to the `ts-tbt-sisl-tutorial`... or does it? It is because I was not completely sure about this that I decided to work directly from the forked repository (`main` branch).

But that is a different matter, `sisl` is a package that is installed, and then you'll have 2 versions available, which sometimes can cause problems if one is not consistent in ones workflow. The tutorials are not installed, they are just files. Hence you won't have that problem.

> If you may clarify me this, then I will go on with your instructions - I may have couple of questions on those, but let me go step by step...
> 
> Thanks for the guidance!

Feel free to ask them as you find them.

**Comment by ialcon** [comment]
> Hmm, no, when working with these tutorials you should preferentially do it in the source tree. :)
> The reason is that you won't copy back things that were already fixed :)

I guess you mean that I was right - so that there is **no** problem in having the original package of your tutorials in one folder, and work in corrections on a cloned folder within my `gitHub/...` folders, correct?

**Comment by ialcon** [comment]
> either approach is fine, as long as you are consistent ;)

I will work following your suggestion in your first comment:

```
git clone git@github.com:zerothi/ts-tbt-sisl-tutorial.git
cd ts-tbt-sisl-tutorial
git remote add mine git@github.com:ialcon/ts-tbt-sisl-tutorial.git
```
and your following points **1-5**. I will go quickly through the `git` documentation, as I have barely tried it really. If I get any issues, I'll let you know.

**Comment by zerothi** [comment]
> > Hmm, no, when working with these tutorials you should preferentially do it in the source tree. :)
> > The reason is that you won't copy back things that were already fixed :)
> 
> I guess you mean that I was right - so that there is **no** problem in having the original package of your tutorials in one folder, and work in corrections on a cloned folder within my `gitHub/...` folders, correct?

Hmm, it depends, I would suggest you work on the tutorials in the same folder as the one cloned, because then you are sure that you are not overwriting old changes. So it seems to me that your workflow isn't what I suggested.

**Pull request merged**
