### PR TITLE
Add conda environment for mybinder 

### PR DESCRIPTION
**Pull request by jan-janssen**
This allows participants to execute the notebooks directly in their browser:
[Binder](https://mybinder.org/v2/gh/jan-janssen/ts-tbt-sisl-tutorial/HEAD?filepath=tutorial.ipynb)

### CODE REVIEW

**Comment by zerothi** [comment]
Many thanks for this!

A couple of questions:
1. I think having this in the `.binder` folder is more appropriate to not spill the main repo.
2. One problem with these tutorials is that they rely on siesta and/or tbtrans which means they will be very hard to run without those, having the binder would perhaps make users think they could run and test everything? However, they can't :( What do you think?

**Comment by jan-janssen** [comment]
I moved the environment file to the `binder` subfolder. https://mybinder.readthedocs.io/en/latest/using/config_files.html#postbuild-run-code-after-installing-the-environment

> 2. One problem with these tutorials is that they rely on siesta and/or tbtrans which means they will be very hard to run without those, having the binder would perhaps make users think they could run and test everything? However, they can't :( What do you think?

Why not? `siesta` is available as conda package, still with the limited resources on mybinder it might be a bit slow.

**Comment by zerothi** [comment]
> Why not? `siesta` is available as conda package, still with the limited resources on mybinder it might be a bit slow.

True. :)
So I have to get to it to update the conda package... It is also overdue...

So I'll wait with merging this (thanks) until siesta 4.1.5 is up (any older versions won't do it).

**Comment by zerothi** [comment]
Oh, and I ment `.binder` (with the dot).
Although the binder documentation does not clarify it works, it does. So I would prefer that :)
But I can do that once I get there.

**Comment by jan-janssen** [comment]
I guess it should be fine to merge this pull request now as you already updated the siesta package https://github.com/conda-forge/siesta-feedstock/pull/21

**Comment by zerothi** [comment]
I would like to double check whether it works. :)

Also, I think we need a dependency for this. sisl>=0.11.0 and siesta>=4.1.5. Then I think we are more good to go!

**Comment by zerothi** [comment]
This is now merged in the 2021 branch!

Thanks!

**Comment by zerothi** [comment]
Note, it is tested but very difficult to complete the tutorials, editing text files in jupyter is not easy!

**Pull request closed without merging**
